CREATE TABLE IF NOT EXISTS players (
    id INT(11) NOT NULL AUTO_INCREMENT,
    identifier VARCHAR(50) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=